# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AppWebTestAzureContainer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: azuretestcontainer.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6F112BC786724C03A849322E268BD400 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_B20F0C2D35524A02B475ED03DE29CC38 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: azuretestcontainer.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6F112BC786724C03A849322E268BD400 }}/next-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AppWebTestAzureContainer'
          slot-name: 'Production'
          images: 'azuretestcontainer.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6F112BC786724C03A849322E268BD400 }}/next-app:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F5BF30F0B3614D6CA1C5A0B66F6DBDD5 }}